# Generated by Django 4.2.4 on 2023-08-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feather_color', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='bird_pictures/')),
            ],
        ),
    ]
